# fly.toml app configuration file generated for audiobookcovers-downloader on 2025-06-09T10:07:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'audiobookcovers-downloader'
primary_region = 'sjc'
swap_size_mb = 1024

[build]

[[restart]]
policy = 'never'
retries = 0


[[vm]]
memory = '2048mb'
cpu_kind = 'performance'
cpus = 1

[env]
AWS_ENDPOINT_URL_S3 = "https://fly.storage.tigris.dev"
AWS_ENDPOINT_URL_IAM = "https://fly.iam.storage.tigris.dev"
AWS_REGION = 'auto'
AWS_S3_BUCKET = 'com-audiobookcovers'
REDDIT_SORT = 'new'
REDDIT_SORT_TIME = 'all'